package middleware

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"reflect"
	"strings"

	"ebike-device-openapi-go/internal/api/dto"
	"ebike-device-openapi-go/internal/pkg/cache"
	"ebike-device-openapi-go/internal/pkg/logger"
	"ebike-device-openapi-go/internal/pkg/metrics"
	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
)

// RouteConfig represents the dynamic configuration snapshot needed by RoutFilter.
type RouteConfig struct {
	Cloud              string
	RouterSwitch       bool
	AnvelinkOpenapiUrl string
	ExcludeUrls        []string
}

// ConfigProvider dynamically provides the latest RouteConfig configuration.
type ConfigProvider func() *RouteConfig

// responseBodyWriter intercepts the response generated by Gin
type responseBodyWriter struct {
	gin.ResponseWriter
	body *bytes.Buffer
}

func (w responseBodyWriter) Write(b []byte) (int, error) {
	w.body.Write(b)
	return w.ResponseWriter.Write(b)
}

func RoutFilter(rdb *redis.Client, configProvider ConfigProvider) gin.HandlerFunc {
	return func(c *gin.Context) {
		reqURL := c.Request.URL.Path

		// Shadow Mode Setup
		javaResultBase64 := c.Request.Header.Get("X-Shadow-Java-Result")
		hasJavaResult := javaResultBase64 != ""

		var isShadow bool
		if hasJavaResult {
			isShadow = true
		} else {
			dryRunEnv := os.Getenv("DRY_RUN")
			isShadow = dryRunEnv == "true" // Default to false
		}

		c.Set("isShadowMode", isShadow)

		var shadowWriter *responseBodyWriter
		if hasJavaResult {
			shadowWriter = &responseBodyWriter{body: bytes.NewBufferString(""), ResponseWriter: c.Writer}
			c.Writer = shadowWriter
		}

		cfg := configProvider()

		// 1. Check if the URL is excluded from routing
		if isExcludeUrl(reqURL, cfg.ExcludeUrls) {
			c.Next()

			// Shadow Compare Logic for excluded URLs (e.g. Uplink)
			if hasJavaResult {
				performShadowCompare(reqURL, c, shadowWriter, javaResultBase64)
			}
			return
		}

		// 2. Read body to extract IMEI
		var bodyBytes []byte
		if c.Request.Body != nil {
			bodyBytes, _ = io.ReadAll(c.Request.Body)
			c.Request.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
		}

		// Try to extract imei from query params first, then from JSON body
		imei := c.Query("imei")
		if imei == "" && len(bodyBytes) > 0 {
			var parsed map[string]interface{}
			if err := json.Unmarshal(bodyBytes, &parsed); err == nil {
				if v, ok := parsed["imei"].(string); ok {
					imei = v
				}
			}
		}

		// 3. Route to anvelink when this instance holds no session for the device
		route(c, rdb, imei, bodyBytes, cfg)

		// Shadow Compare Logic for routed URLs (e.g. Downlink)
		if hasJavaResult {
			performShadowCompare(reqURL, c, shadowWriter, javaResultBase64)
		}
	}
}

func parseNestedJSON(m map[string]interface{}) {
	if data, ok := m["data"].(map[string]interface{}); ok {
		if decodeBodyStr, ok := data["decodeBody"].(string); ok && decodeBodyStr != "" {
			var nestedMap map[string]interface{}
			if err := json.Unmarshal([]byte(decodeBodyStr), &nestedMap); err == nil {
				data["decodeBody"] = nestedMap
			}
		}
		if resultStr, ok := data["result"].(string); ok && resultStr != "" {
			var nestedMap map[string]interface{}
			if err := json.Unmarshal([]byte(resultStr), &nestedMap); err == nil {
				data["result"] = nestedMap
			}
		}
		if payloadStr, ok := data["payload"].(string); ok && payloadStr != "" {
			var nestedMap map[string]interface{}
			if err := json.Unmarshal([]byte(payloadStr), &nestedMap); err == nil {
				data["payload"] = nestedMap
			}
		}
	}
}

func performShadowCompare(reqURL string, c *gin.Context, shadowWriter *responseBodyWriter, javaResultBase64 string) {
	goResultStr := shadowWriter.body.String()

	javaResultBytes, err := base64.StdEncoding.DecodeString(javaResultBase64)
	if err != nil {
		logger.Log.Error("shadow compare base64 decode failed", zap.String("path", reqURL), zap.Error(err))
		return
	}
	javaResultStr := string(javaResultBytes)

	var goMap, javaMap map[string]interface{}
	errGo := json.Unmarshal([]byte(goResultStr), &goMap)
	errJava := json.Unmarshal(javaResultBytes, &javaMap)

	if errGo != nil || errJava != nil {
		// Fallback to string comparison
		if goResultStr != javaResultStr {
			logger.Log.Warn("shadow compare diff", zap.String("path", reqURL), zap.String("java", javaResultStr), zap.String("go", goResultStr))
		} else {
			logger.Log.Info("shadow compare match", zap.String("path", reqURL), zap.String("mode", "string"))
		}
		return
	}

	// Smart parse nested stringified JSON like decodeBody
	parseNestedJSON(goMap)
	parseNestedJSON(javaMap)

	// Strip nil values handled by omitempty tags now

	// Ignore fields that are mocked in shadow mode for downlink commands
	if strings.HasPrefix(reqURL, "/ebike/cmd/") {
		if dataGo, ok := goMap["data"].(map[string]interface{}); ok {
			delete(dataGo, "jobId")
			delete(dataGo, "result")
			delete(dataGo, "payload")
		}
		if dataJava, ok := javaMap["data"].(map[string]interface{}); ok {
			delete(dataJava, "jobId")
			delete(dataJava, "result")
			delete(dataJava, "payload")
		}
	}

	if !reflect.DeepEqual(goMap, javaMap) {
		logger.Log.Warn("shadow compare diff", zap.String("path", reqURL), zap.String("java", javaResultStr), zap.String("go", goResultStr))
	} else {
		logger.Log.Info("shadow compare match", zap.String("path", reqURL))
	}
}

// isExcludeUrl checks if a URL is excluded from routing.
func isExcludeUrl(url string, excludeUrls []string) bool {
	// Uplink paths are always handled locally.
	if strings.HasPrefix(strings.ToLower(url), "/device-gateway/") {
		return true
	}
	for _, e := range excludeUrls {
		if strings.Contains(url, e) {
			return true
		}
	}
	return false
}

// route forwards to anvelink when this cluster holds no session for the device.
func route(c *gin.Context, rdb *redis.Client, imei string, bodyBytes []byte, cfg *RouteConfig) {
	needRouteVal := needRoute(c, rdb, imei) && cfg.RouterSwitch
	if needRouteVal {
		urlStr := getFullRouteUrl(c.Request, cfg.AnvelinkOpenapiUrl)
		doRouter(c, urlStr, bodyBytes, cfg.Cloud, "网关网络异常-OLD")
	} else {
		c.Next()
	}
}

// needRoute checks if the local cache contains the EcuLogin, returning true if we need to route.
func needRoute(c *gin.Context, rdb *redis.Client, imei string) bool {
	if imei == "" {
		return true
	}

	key := "ecu_login_" + imei // ECU_HOST in Java defaults to Aliyun key prefix
	val, err := rdb.Get(c.Request.Context(), key).Result()
	if err == nil && val != "" {
		var ecuLogin dto.EcuLogin
		if err := json.Unmarshal([]byte(val), &ecuLogin); err == nil {
			cache.DefaultEcuLoginCache.Put(imei, &ecuLogin)
			c.Set("ecuLogin", &ecuLogin)
			return false
		}
	}

	// Redis miss or error — fall back to local Caffeine-equivalent cache (Java RoutFilter.needRoute).
	if cached := cache.DefaultEcuLoginCache.Get(imei); cached != nil {
		c.Set("ecuLogin", cached)
		return false
	}

	if err != nil {
		if errors.Is(err, redis.Nil) {
			// Key absent is a normal miss (device not yet logged in / just disconnected);
			// since all devices live in the same cluster this is a transient login-race
			// window, not a fault. Keep it at debug to avoid log noise.
			logger.Log.Debug("router login key absent", zap.String("imei", imei))
		} else {
			// A non-nil error means an actual Redis fault (timeout, connection loss, ...).
			logger.Log.Warn("router redis lookup failed", zap.String("imei", imei), zap.Error(err))
		}
	}
	return true
}

// getFullRouteUrl builds the target URL using HTTP scheme.
func getFullRouteUrl(req *http.Request, domain string) string {
	targetDomain := strings.TrimSpace(domain)
	if !strings.HasPrefix(targetDomain, "http://") && !strings.HasPrefix(targetDomain, "https://") {
		targetDomain = "http://" + targetDomain
	}

	reqURI := req.URL.Path
	if req.URL.RawQuery != "" {
		return targetDomain + reqURI + "?" + req.URL.RawQuery
	}
	return targetDomain + reqURI
}

// doRouter performs the reverse proxying and sets the cloud tracking headers.
func doRouter(c *gin.Context, targetURL string, bodyBytes []byte, cloud string, errMsg string) {
	remote, err := url.Parse(targetURL)
	if err != nil {
		logger.Log.Error("doRouter invalid target URL", zap.String("targetURL", targetURL), zap.Error(err))
		c.JSON(http.StatusOK, dto.Result{Success: false, Code: "10001", Msg: errMsg})
		c.Abort()
		return
	}

	proxy := httputil.NewSingleHostReverseProxy(&url.URL{
		Scheme: remote.Scheme,
		Host:   remote.Host,
	})

	originalDirector := proxy.Director
	proxy.Director = func(req *http.Request) {
		originalDirector(req)
		req.URL.Path = remote.Path
		req.URL.RawQuery = remote.RawQuery
		// Propagate cloud header to prevent infinite routing loop
		req.Header.Add("cloud", cloud)
	}

	c.Request.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
	metrics.IncRouteProxy()

	proxy.ErrorHandler = func(w http.ResponseWriter, r *http.Request, err error) {
		logger.Log.Error("doRouter proxy error", zap.String("targetURL", targetURL), zap.Error(err))
		w.Header().Set("Content-Type", "application/json;charset=UTF-8")
		w.WriteHeader(http.StatusOK)
		resBytes, _ := json.Marshal(dto.Result{Success: false, Code: "10001", Msg: errMsg})
		w.Write(resBytes)
	}

	proxy.ServeHTTP(c.Writer, c.Request)
	c.Abort()
}
