// apigen scans Java ebike-fence-api *Api.java files and generates Go route manifest.
//
//	go run ./tools/apigen -java-api D:/workspace/ebike/ebike-fence/ebike-fence-api/src/main/java/com/xyy/ebike/fence/api -out internal/api
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

var (
	rePostMapping = regexp.MustCompile(`@PostMapping\s*\(\s*"(/[^"]+)"\s*\)`)
	reClassPrefix = map[string]string{
		"RidingCarConfigApi": "config",
	}
)

type route struct {
	Method      string
	Path        string
	HandlerName string
	ApiModule   string
}

func main() {
	javaAPI := flag.String("java-api", "", "path to com/xyy/ebike/fence/api directory")
	outDir := flag.String("out", "internal/api", "output directory for routes_gen.go")
	flag.Parse()

	if *javaAPI == "" {
		fmt.Fprintln(os.Stderr, "java-api path required")
		os.Exit(1)
	}

	var routes []route
	entries, err := os.ReadDir(*javaAPI)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), "Api.java") {
			continue
		}
		apiName := strings.TrimSuffix(e.Name(), ".java")
		data, err := os.ReadFile(filepath.Join(*javaAPI, e.Name()))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		prefix := reClassPrefix[apiName]
		for _, m := range rePostMapping.FindAllStringSubmatch(string(data), -1) {
			p := m[1]
			if prefix != "" && !strings.HasPrefix(p, "/"+prefix) {
				p = "/" + strings.Trim(prefix, "/") + p
			}
			routes = append(routes, route{
				Method:      "POST",
				Path:        p,
				HandlerName: pathToHandlerName(p),
				ApiModule:   apiName,
			})
		}
	}

	// Actuator (not in Feign Api)
	routes = append(routes, route{
		Method: "POST", Path: "/actuator/deregisterService",
		HandlerName: "HandleActuatorDeregisterService", ApiModule: "Actuator",
	})

	sort.Slice(routes, func(i, j int) bool { return routes[i].Path < routes[j].Path })

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	outPath := filepath.Join(*outDir, "routes_gen.go")
	if err := os.WriteFile(outPath, []byte(renderRoutesGo(routes)), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %d routes -> %s\n", len(routes), outPath)
}

func pathToHandlerName(path string) string {
	path = strings.TrimPrefix(path, "/")
	var b strings.Builder
	b.WriteString("Handle")
	for _, part := range strings.Split(path, "/") {
		for _, seg := range strings.FieldsFunc(part, func(r rune) bool {
			return r == '-' || r == '_'
		}) {
			if seg == "" {
				continue
			}
			b.WriteString(title(seg))
		}
	}
	return b.String()
}

func title(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func renderRoutesGo(routes []route) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/apigen; DO NOT EDIT.\n")
	b.WriteString("package api\n\n")
	b.WriteString("type GeneratedRoute struct {\n")
	b.WriteString("\tMethod      string\n")
	b.WriteString("\tPath        string\n")
	b.WriteString("\tHandlerName string\n")
	b.WriteString("\tApiModule   string\n")
	b.WriteString("}\n\n")
	b.WriteString("func GeneratedRoutes() []GeneratedRoute {\n")
	b.WriteString("\treturn []GeneratedRoute{\n")
	for _, r := range routes {
		b.WriteString(fmt.Sprintf("\t\t{Method:%q, Path:%q, HandlerName:%q, ApiModule:%q},\n",
			r.Method, r.Path, r.HandlerName, r.ApiModule))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}
