---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: push-notification
  name: push-notification
  namespace: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: push-notification
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: push-notification
        lang: go
    spec:
      containers:
        - env:
            - name: NACOS_SERVER_ADDR
              value: '192.168.2.20:8848'
            - name: NACOS_NAMESPACE
              value: prod
            - name: NACOS_GROUP
              value: xyy
          image: >-
            registry.cn-shanghai.aliyuncs.com/ebike_luoping/push-notification-go:v1.0.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: push-notification
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /logs
              name: volume-localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: volume-localtime

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: push-notification
  name: push-notification
  namespace: prod
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: push-notification
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-weight: ''
  labels:
    app: push-notification
  name: push-notification
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: notify.luopingtech.com
      http:
        paths:
          - backend:
              service:
                name: push-notification
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
