apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ebike-device-openapi
  name: ebike-device-openapi
  namespace: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ebike-device-openapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ebike-device-openapi
        lang: go
    spec:
      containers:
        - env:
            - name: GIN_MODE
              value: release
            - name: NACOS_SERVER_ADDR
              value: '192.168.2.20:8848'
            - name: NACOS_NAMESPACE
              value: prod
            - name: NACOS_GROUP
              value: xyy
            - name: DRY_RUN
              value: "false"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: registry.cn-shanghai.aliyuncs.com/ebike_luoping/ebike-device-openapi-go:v1.0.43
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: ebike-device-openapi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /logs
              name: volume-localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: volume-localtime

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ebike-device-openapi
  name: ebike-device-openapi
  namespace: prod
spec:
  clusterIPs: []
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ebike-device-openapi
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: ebike-device-openapi
  name: ebike-device-openapi
  namespace: prod
spec:
  rules:
    - host: openapi.luopingtech.com
      http:
        paths:
          - backend:
              service:
                name: ebike-device-openapi
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
