package service

import (
	"encoding/json"

	"ebike-open-paas-go/internal/client"
	"ebike-open-paas-go/internal/contract"
	"ebike-open-paas-go/internal/pkg/config"
)

// CommandOpts carries optional voice / TBeacon fields shared by control APIs.
type CommandOpts struct {
	Idx       *int
	Volume    *int
	IsTBeacon *int
}

func baseCommand(tenantID, imei string, opts CommandOpts) map[string]interface{} {
	body := map[string]interface{}{
		"imei":           imei,
		"async":          false,
		"commandContext": client.CommandContext(tenantID, ""),
	}
	if opts.Idx != nil {
		body["idx"] = *opts.Idx
	}
	if opts.Volume != nil {
		body["volume"] = *opts.Volume
	}
	if opts.IsTBeacon != nil {
		body["isTBeacon"] = *opts.IsTBeacon
	}
	return body
}

func commandCode(cr *client.CommandResult, err error, tbeacon bool) (int, error) {
	if err != nil {
		if ge, ok := err.(*client.GatewayError); ok {
			code := contract.MapEcuCode(ge.Code)
			if tbeacon && ge.Code == "136" {
				return contract.CodeNoTBeacon, nil
			}
			return code, nil
		}
		return contract.CodeServerInternal, err
	}
	code := contract.MapEcuCode(cr.EcuCodeString())
	if tbeacon && cr.EcuCodeString() == "142" {
		return contract.CodeNoTBeacon, nil
	}
	return code, nil
}

// AccControl maps to paas /device/paas/lock.
func AccControl(tenantID, imei string, acc int, opts CommandOpts) (int, error) {
	body := baseCommand(tenantID, imei, opts)
	body["acc"] = acc
	cr, err := client.PostPaasCommand("/device/paas/lock", body)
	return commandCode(cr, err, opts.IsTBeacon != nil && *opts.IsTBeacon == 1)
}

// DefendControl maps to paas /device/paas/defend.
func DefendControl(tenantID, imei string, defend int, opts CommandOpts) (int, error) {
	body := baseCommand(tenantID, imei, opts)
	body["defend"] = defend
	cr, err := client.PostPaasCommand("/device/paas/defend", body)
	return commandCode(cr, err, opts.IsTBeacon != nil && *opts.IsTBeacon == 1)
}

// LockControl orchestrates Xiaoan's combined lock/unlock.
// locked=1 (lock) -> acc=0; locked=0 (unlock) -> acc=1 (also undefend).
func LockControl(tenantID, imei string, locked int, opts CommandOpts) (int, error) {
	acc := 0
	if locked == 0 {
		acc = 1
	}
	return AccControl(tenantID, imei, acc, opts)
}

// BackWheelControl maps locked -> sw with inverted polarity.
// Xiaoan locked 1=lock -> internal sw 0; locked 0=unlock -> sw 1.
func BackWheelControl(tenantID, imei string, locked int, opts CommandOpts) (int, error) {
	sw := 1
	if locked == 1 {
		sw = 0
	}
	body := baseCommand(tenantID, imei, opts)
	body["sw"] = sw
	cr, err := client.PostPaasCommand("/device/paas/rearWheelLock", body)
	return commandCode(cr, err, false)
}

// BatteryCompartmentControl maps locked -> sw with the same polarity.
func BatteryCompartmentControl(tenantID, imei string, locked int, opts CommandOpts) (int, error) {
	body := baseCommand(tenantID, imei, opts)
	body["sw"] = locked
	cr, err := client.PostPaasCommand("/device/paas/batteryCompartment", body)
	return commandCode(cr, err, false)
}

// DeviceVoice plays a ringtone. index is remapped via open.voiceIndexMap.
func DeviceVoice(tenantID, imei string, index, volume int) (int, error) {
	idx := index
	if m := config.GlobalConfig().Open.VoiceIndexMap; m != nil {
		if mapped, ok := m[index]; ok {
			idx = mapped
		}
	}
	body := map[string]interface{}{
		"imei":           imei,
		"idx":            idx,
		"async":          false,
		"commandContext": client.CommandContext(tenantID, ""),
	}
	if volume > 0 {
		body["volume"] = volume
	}
	cr, err := client.PostPaasCommand("/device/paas/voice", body)
	return commandCode(cr, err, false)
}

// Bluetooth configures BLE token/name.
//
// The response's `tm` is generated by the caller from the wall clock: paas
// answers with BluetoothCo{token,name} and no timestamp, so there is nothing
// upstream to forward. The previous signature returned an int64 that was always
// zero, which read like an upstream value the handler was choosing to ignore.
func Bluetooth(tenantID, imei string, token *int64, name string) (int, error) {
	body := map[string]interface{}{
		"imei":           imei,
		"async":          false,
		"commandContext": client.CommandContext(tenantID, ""),
	}
	if token != nil {
		body["token"] = *token
	}
	if name != "" {
		body["name"] = name
	}
	cr, err := client.PostPaasCommand("/device/paas/bluetooth", body)
	return commandCode(cr, err, false)
}

// Reboot restarts the device.
func Reboot(tenantID, imei string) (int, error) {
	body := map[string]interface{}{
		"imei":           imei,
		"async":          false,
		"commandContext": client.CommandContext(tenantID, ""),
	}
	cr, err := client.PostPaasCommand("/device/paas/restart", body)
	return commandCode(cr, err, false)
}

// SetLimitSpeed calls openapi /set_limit_speed directly (no AES on that path).
func SetLimitSpeed(tenantID, imei string, speed int) (int, error) {
	env, err := client.PostOpenapi("/set_limit_speed", map[string]interface{}{
		"imei":           imei,
		"speed":          speed,
		"async":          false,
		"commandContext": client.CommandContext(tenantID, ""),
	}, tenantID)
	if err != nil {
		return contract.CodeServerInternal, err
	}
	var cr client.CommandResult
	if len(env.Data) > 0 {
		unmarshalLoose(env.Data, &cr)
		if cr.EcuCode == nil && env.Success {
			if code := extractNestedCode(env.Data); code != "" {
				c := code
				cr.EcuCode = &c
			}
		}
	}
	if !env.Success && cr.EcuCode == nil {
		return contract.MapEcuCode(env.Code), nil
	}
	return contract.MapEcuCode(cr.EcuCodeString()), nil
}

func unmarshalLoose(data []byte, out *client.CommandResult) {
	_ = json.Unmarshal(data, out)
}

func extractNestedCode(data []byte) string {
	var m map[string]interface{}
	if json.Unmarshal(data, &m) != nil {
		return ""
	}
	if s, ok := m["result"].(string); ok {
		var inner map[string]interface{}
		if json.Unmarshal([]byte(s), &inner) == nil {
			return AsString(inner["code"])
		}
	}
	return AsString(m["ecuCode"])
}
